In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ['la comida es rica',
        'restaurante muy bueno',
        'demasiado bueno',
        'me gusto mucho',
        'volveria de nuevo',
        'concina horible',
        'nunca ir aqui',
        'servicio pesimo',
        'calidad pesima',
        'cocina mejorable']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("restaurante muy bueno",30)

[28, 18, 6]

In [ ]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[7, 6, 9, 28],
 [28, 18, 6],
 [3, 6],
 [21, 4, 28],
 [4, 18, 3],
 [9, 13],
 [16, 13, 20],
 [5, 13],
 [20, 17],
 [4, 9]]

In [ ]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[ 7,  6,  9, 28],
       [28, 18,  6,  0],
       [ 3,  6,  0,  0],
       [21,  4, 28,  0],
       [ 4, 18,  3,  0],
       [ 9, 13,  0,  0],
       [16, 13, 20,  0],
       [ 5, 13,  0,  0],
       [20, 17,  0,  0],
       [ 4,  9,  0,  0]], dtype=int32)

In [ ]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X, y, epochs=50, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 157ms/step - loss: 0.5978 - accuracy: 0.9000


0.8999999761581421

In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [ ]:
weights[13]

array([ 0.02567121, -0.09422053,  0.03812515, -0.08888284, -0.0925156 ],
      dtype=float32)

In [ ]:
weights[4]

array([-0.02127583,  0.0148026 , -0.04409596,  0.09255254,  0.00249244],
      dtype=float32)